"""Adicionado Usuario e relacionamentos

Revision ID: 2114decbb435
Revises: e63471fe7d87
Create Date: 2021-06-01 10:50:26.606562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2114decbb435'
down_revision = 'e63471fe7d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('detalhes', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('tamanho', sa.String(), nullable=True),
    sa.Column('Usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Usuario_id'], ['usuario.id'], name='fk_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legenda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legenda_id'), ['id'], unique=False)

    with op.batch_alter_table('Legenda', schema=None) as batch_op:
        batch_op.drop_index('ix_Legenda_id')

    op.drop_table('Legenda')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Legenda',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('pais', sa.VARCHAR(), nullable=True),
    sa.Column('genero', sa.VARCHAR(), nullable=True),
    sa.Column('ano', sa.INTEGER(), nullable=True),
    sa.Column('tamanho', sa.VARCHAR(), nullable=True),
    sa.Column('detalhes', sa.VARCHAR(), nullable=True),
    sa.Column('disponivel', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Legenda', schema=None) as batch_op:
        batch_op.create_index('ix_Legenda_id', ['id'], unique=False)

    with op.batch_alter_table('legenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legenda_id'))

    op.drop_table('legenda')
    # ### end Alembic commands ###
