"""Inicial

Revision ID: 841622bda0bb
Revises: 
Create Date: 2021-05-23 11:47:40.890559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841622bda0bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
