"""Nova coluna Tamanho

Revision ID: c09c202c715c
Revises: 841622bda0bb
Create Date: 2021-05-23 11:54:21.088322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09c202c715c'
down_revision = '841622bda0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Legenda', sa.Column('tamanho', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Legenda', 'tamanho')
    # ### end Alembic commands ###
