"""Adicionado Relacionamento

Revision ID: e63471fe7d87
Revises: c09c202c715c
Create Date: 2021-05-23 12:19:38.297850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63471fe7d87'
down_revision = 'c09c202c715c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Legenda', sa.Column('detalhes', sa.String(), nullable=True))
    op.add_column('Legenda', sa.Column('disponivel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Legenda', 'disponivel')
    op.drop_column('Legenda', 'detalhes')
    # ### end Alembic commands ###
